name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Qt        
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.*
          arch: gcc_64
          dir: '${{github.workspace}}/'

      - name: Build
        shell: bash
        run: |
          git submodule update --recursive --remote --init
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --parallel $(nproc)
          mkdir Linux
          mv Plume Linux/

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: "Plume - Linux x64"
          path: '${{github.workspace}}/build/Linux'
