name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Qt        
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.6.*
          arch: gcc_64
          dir: '${{github.workspace}}/'

      - name: Build libical
        shell: bash
        run: |
          git submodule update --init --recursive
          cd libs/libical
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_CXX_BINDINGS=False -DLIBICAL_BUILD_TESTING=False -DENABLE_GTK_DOC=False -DICAL_GLIB=False -DGOBJECT_INTROSPECTION=False -DICAL_GLIB_VAPI=False
          make -j $(nproc)
          sudo make install

      - name: Build
        shell: bash
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --parallel $(nproc)
          mkdir Linux
          mv Plume Linux/

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: "Plume - Linux x64"
          path: '${{github.workspace}}/build/Linux'
